eval_per_marker: true
# Weave configuration
weave:
  entity: "ip-ai"
  project_name: "eval-inv-gen-new-latest-trails-test"
  skip_wandb: true

# Statistics configuration
statistics:
  num_trials: 2 # number of trials to run
  confidence_level: 0.95 # confidence level for the confidence interval

# Evaluation configuration
dataset:
  # https://huggingface.co/datasets/idopinto/invbench-eval-uautomizer25-k3-full
  name: "idopinto/invbench-eval-uautomizer25-k3-l40s-full" 
  limit: 10 # number of samples to evaluate -1 for all
  prefix: "" # prefix to filter files by (useful for testing also)
  split: "hard" # split to evaluate on
  re_split: true # re-split the dataset by difficultiy threshold
  difficulty_threshold: 15 # difficulty threshold for easy/hard split in seconds

# Scorer configuration
scorer:
  # currently only uautomizer is supported
  verifier:
    version: "25"
    property: "unreach-call.prp"
    arch: "32bit"
    timeout_seconds: 600.0
  baseline_is_timeout: false # when true, the verifier timeout is always set to baseline timeout (useful to accelerate evaluation)

# Prompt templates 
prompts:
  per_marker_system_prompt: |
    You are an expert C programmer and highly proficient in generating strong loop invariants for C programs that accelerate traditional verifiers' verification process.

    ## Input format
    - A C program instrumented with loop markers of the form: 
      ```c
      INVARIANT_MARKER_k();  // appears at the *start of each loop body*
      ```
      - The program contains a single target property as an assertion of the form:
      ```c
      assert(<target_property>);
      ```
    - A target loop marker (e.g., "INVARIANT_MARKER_1")

    ## Task
    - Propose ONE loop invariant that is intended to hold specifically at the target loop marker.
    - The invariant should help prove the target property and be inductive if possible.

    ## Output format
    - Output MUST be a single JSON object on one line wrapped in ```json``` tags and nothing else.
    - The JSON MUST have exactly these keys:
      - "marker": MUST be exactly the target loop marker (e.g., "INVARIANT_MARKER_1")
      - "content": ONLY a valid C boolean expression for the invariant. 

    ## Output format example
    ```json
    {"marker":"<target_marker>","content":"<content>"}
    ```

  per_marker_user_prompt_template: |
      ## User Input
      ### C Program
      ```c
      {program}
      ```

      ### Target Loop Marker
      {target_marker}

  non_det_explanation: |
    __VERIFIER_nondet_X(): In order to model nondeterministic values, the following functions can be assumed to return an arbitrary value of the indicated type: __VERIFIER_nondet_X() with X in {bool, char, int, int128, float, double, loff_t, long, longlong, pchar, pthread_t, sector_t, short, size_t, u32, uchar, uint, uint128, ulong, ulonglong, unsigned, ushort} (no side effects, pointer for void *, etc.). 
    You may assume that the functions are implemented according to the following template:
    X __VERIFIER_nondet_X() {{ X val; return val; }}

# Model and task configuration
defaults:
   - _self_ # load the default configuration
   - models: qwen_no_think_config # oss or qwen_config

# Examples:
#  uv run -m src.eval.evaluate models=openai_config dataset.limit=1
#  uv run -m src.eval.evaluate models=qwen_config dataset.limit=1
#  uv run -m src.eval.evaluate models=oss_config dataset.limit=1

#  uv run -m src.eval.evaluate_vbs models=qwen_no_think_config
