defaults:
  - _family/together_api@_here_
  - _self_

label: gpt_oss_20b
base_model:
  id: "openai/gpt-oss-20b"
  sampling_params:
    temperature: 1.0
    max_tokens: 16384
    reasoning_effort: "medium"
