label: llama3_8b
client: hf
eval_ft_model: false

base_model:
  id: "meta-llama/Llama-3.1-8B-Instruct"
  attn_implementation: "flash_attention_2"
  sampling_params:
    # Meta-recommended sampling params for Llama 3.1 Instruct
    # https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct
    max_new_tokens: 1024
    temperature: 0.6
    top_p: 0.9
    do_sample: true

ft_model:
  sft_version: "v0"
  id: "idopinto/llama3-8b-gen-inv-sft-${.sft_version}-latest"
  is_lora: true

# https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct
# Base model (hard split)
#   sbatch --job-name=me_llama38b scripts/eval/run_multi_eval.sbatch multi_run.num_runs=3 dataset.limit=-1 models=llama3_8b_config dataset.split=hard weave.project_name=eval-wonda-baselines
