client: hf # or vllm / together
eval_ft_model: false

vllm: # vLLM-specific config (only used when client=vllm)
  base_url: "http://localhost:8000/v1"
  model: "gen_inv_adapter" # LoRA adapter name or base model name

base_model:
  # id: "openai/gpt-oss-120b"
  id: "openai/gpt-oss-20b"
  # reasoning_effort: "low"
  sampling_params:
    max_new_tokens: 16384
    temperature: 1.0
    top_p: 1.0
    top_k: 0.0
  extra_body: 
    include_reasoning: True
    reasoning_effort: "low"
ft_model:
  id: "idopinto/gpt-oss-20b-gen-inv-sft-perloc"
  is_lora: true

# https://huggingface.co/collections/openai/gpt-oss