client: hf # or vllm / together
eval_ft_model: false

vllm: #  vLLM-specific config (only used when client=vllm)
  base_url: "http://localhost:8000/v1"
  model: "gen_inv_adapter" # LoRA adapter name or base model name

base_model: 
  # id: "Qwen/Qwen3-32B"
  # id: "Qwen/Qwen3-14B"
  # id: "Qwen/Qwen3-8"
  # id: "Qwen/Qwen3-4B"
  # id: "Qwen/Qwen3-1.7B"
  id: "Qwen/Qwen3-0.6B"
  sampling_params:
    max_new_tokens: 32768
    temperature: 0.6
    top_p: 0.95
    top_k: 20
    min_p: 0
  extra_body:   
    enable_thinking: false

ft_model:
  id: "idopinto/qwen3-0.6b-gen-inv-sft-v0"
  # id: "idopinto/qwen-3-0.6b-gen-inv-sft-v1"
  is_lora: false

# https://huggingface.co/collections/Qwen/qwen3