defaults:
  - _family/hf_qwen_t@_here_
  - _self_

label: qwen3_8b_t
base_model:
  id: "Qwen/Qwen3-8B"
ft_model:
  sft_version: "v0"
  id: "idopinto/qwen3-8b-t-gen-inv-sft-${.sft_version}-latest"
  is_lora: true
