#include <assert.h>
void reach_error(void) { assert(0); }

extern int __VERIFIER_nondet_int(void);
extern _Bool __VERIFIER_nondet_bool(void);

void __VERIFIER_assert(int cond) {
    if (!cond) {
        reach_error();
    }
}

/*
  New Program:
  This program checks if the sequence of numbers generated by repeatedly executing
  x = x + y, y = y - 1 can maintain certain properties.
  Preconditions: x >= 0, y >= 0
  Postcondition: The sum of x and y is non-decreasing.
*/
int main() {
    int x = __VERIFIER_nondet_int();
    int y = __VERIFIER_nondet_int();

    if (!(x >= 0 && y >= 0)) {
        return 0;
    }

    int initial_sum = x + y;

    while (__VERIFIER_nondet_bool()) {
        if (y == 0) {
            break; // Stop if y becomes 0 to avoid infinite loop
        }
        x = x + y;
        y = y - 1;
    }

    __VERIFIER_assert((x + y) >= initial_sum);
    return 0;
}