defaults:
  - _family/qwen_lora@_here_
  - _shared/prompts@prompts: wonda
  - _self_

model:
  base_model_name: "Qwen/Qwen3-14B"

sft:
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 8
  learning_rate: 5e-5
  eval_steps: 5
